### ISSUE TITLE
What to type in the wifi device?

### ISSUE THREAD

**Issue by officialasishkumar** [adarshkrdubay/AKDFI#2]
![image](https://github.com/adarshkrdubay/AKDFI/assets/87874775/b6a2a0ec-8a96-4d0b-bd87-cfb85a306731)
What to type here?

**Comment by adarshkrdubay** [comment]
I haven't updated this code since last year, so it remains a basic script. Your error is tied to the Wi-Fi interface name, so please change the Wi-Fi interface names on lines 86 and 98 to match your actual interface name. I will just update the version, and I apologize for any inconvenience.
